# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `curses` gem.
# Please instead update this file by running `bin/tapioca gem curses`.


# pkg:gem/curses#lib/curses.rb:12
module Curses
  private

  # pkg:gem/curses#lib/curses.rb:12
  def ESCDELAY; end

  # pkg:gem/curses#lib/curses.rb:12
  def ESCDELAY=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def TABSIZE; end

  # pkg:gem/curses#lib/curses.rb:12
  def TABSIZE=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def addch(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def addstr(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def assume_default_colors(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def attroff(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def attron(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def attrset(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def beep; end

  # pkg:gem/curses#lib/curses.rb:12
  def bkgd(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def bkgdset(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def can_change_color?; end

  # pkg:gem/curses#lib/curses.rb:12
  def cbreak; end

  # pkg:gem/curses#lib/curses.rb:93
  def chgat(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/curses#lib/curses.rb:12
  def clear; end

  # pkg:gem/curses#lib/curses.rb:12
  def close_screen; end

  # pkg:gem/curses#lib/curses.rb:12
  def closed?; end

  # pkg:gem/curses#lib/curses.rb:12
  def clrtoeol; end

  # pkg:gem/curses#lib/curses.rb:12
  def color_content(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def color_pair(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def color_pairs; end

  # pkg:gem/curses#lib/curses.rb:12
  def colors; end

  # pkg:gem/curses#lib/curses.rb:12
  def cols; end

  # pkg:gem/curses#lib/curses.rb:12
  def crmode; end

  # pkg:gem/curses#lib/curses.rb:12
  def curs_set(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def def_prog_mode; end

  # pkg:gem/curses#lib/curses.rb:12
  def delch; end

  # pkg:gem/curses#lib/curses.rb:12
  def deleteln; end

  # pkg:gem/curses#lib/curses.rb:12
  def doupdate; end

  # pkg:gem/curses#lib/curses.rb:12
  def echo; end

  # pkg:gem/curses#lib/curses.rb:12
  def erase; end

  # pkg:gem/curses#lib/curses.rb:12
  def flash; end

  # pkg:gem/curses#lib/curses.rb:12
  def flushinp; end

  # pkg:gem/curses#lib/curses.rb:12
  def get_char; end

  # pkg:gem/curses#lib/curses.rb:12
  def getch; end

  # pkg:gem/curses#lib/curses.rb:12
  def getmouse; end

  # pkg:gem/curses#lib/curses.rb:12
  def getstr; end

  # pkg:gem/curses#lib/curses.rb:12
  def has_colors?; end

  # pkg:gem/curses#lib/curses.rb:12
  def inch; end

  # pkg:gem/curses#lib/curses.rb:12
  def init_color(_arg0, _arg1, _arg2, _arg3); end

  # pkg:gem/curses#lib/curses.rb:12
  def init_pair(_arg0, _arg1, _arg2); end

  # pkg:gem/curses#lib/curses.rb:12
  def init_screen; end

  # pkg:gem/curses#lib/curses.rb:12
  def insch(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def insertln; end

  # pkg:gem/curses#lib/curses.rb:12
  def keyboard_encoding; end

  # pkg:gem/curses#lib/curses.rb:12
  def keyboard_encoding=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def keyname(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def lines; end

  # pkg:gem/curses#lib/curses.rb:12
  def mouseinterval(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def mousemask(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def nl; end

  # pkg:gem/curses#lib/curses.rb:12
  def nocbreak; end

  # pkg:gem/curses#lib/curses.rb:12
  def nocrmode; end

  # pkg:gem/curses#lib/curses.rb:12
  def noecho; end

  # pkg:gem/curses#lib/curses.rb:12
  def nonl; end

  # pkg:gem/curses#lib/curses.rb:12
  def noraw; end

  # pkg:gem/curses#lib/curses.rb:12
  def pair_content(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def pair_number(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def raw; end

  # pkg:gem/curses#lib/curses.rb:12
  def refresh; end

  # pkg:gem/curses#lib/curses.rb:12
  def reset_color_pairs; end

  # pkg:gem/curses#lib/curses.rb:12
  def reset_prog_mode; end

  # pkg:gem/curses#lib/curses.rb:12
  def resize(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def resizeterm(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def scrl(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def setpos(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def setscrreg(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def standend; end

  # pkg:gem/curses#lib/curses.rb:12
  def standout; end

  # pkg:gem/curses#lib/curses.rb:12
  def start_color; end

  # pkg:gem/curses#lib/curses.rb:12
  def stdscr; end

  # pkg:gem/curses#lib/curses.rb:12
  def support_extended_colors?; end

  # pkg:gem/curses#lib/curses.rb:12
  def terminal_encoding; end

  # pkg:gem/curses#lib/curses.rb:12
  def terminal_encoding=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def timeout=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def unget_char(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def ungetch(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def ungetmouse(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def use_default_colors; end

  class << self
    # pkg:gem/curses#lib/curses.rb:12
    def ESCDELAY; end

    # pkg:gem/curses#lib/curses.rb:12
    def ESCDELAY=(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def TABSIZE; end

    # pkg:gem/curses#lib/curses.rb:12
    def TABSIZE=(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def addch(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def addstr(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def assume_default_colors(_arg0, _arg1); end

    # pkg:gem/curses#lib/curses.rb:12
    def attroff(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def attron(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def attrset(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def beep; end

    # pkg:gem/curses#lib/curses.rb:12
    def bkgd(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def bkgdset(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def can_change_color?; end

    # pkg:gem/curses#lib/curses.rb:12
    def cbreak; end

    # pkg:gem/curses#lib/curses.rb:93
    def chgat(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/curses#lib/curses.rb:12
    def clear; end

    # pkg:gem/curses#lib/curses.rb:12
    def close_screen; end

    # pkg:gem/curses#lib/curses.rb:12
    def closed?; end

    # pkg:gem/curses#lib/curses.rb:12
    def clrtoeol; end

    # pkg:gem/curses#lib/curses.rb:12
    def color_content(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def color_pair(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def color_pairs; end

    # pkg:gem/curses#lib/curses.rb:12
    def colors; end

    # pkg:gem/curses#lib/curses.rb:12
    def cols; end

    # pkg:gem/curses#lib/curses.rb:12
    def crmode; end

    # pkg:gem/curses#lib/curses.rb:12
    def curs_set(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def def_prog_mode; end

    # pkg:gem/curses#lib/curses.rb:12
    def delch; end

    # pkg:gem/curses#lib/curses.rb:12
    def deleteln; end

    # pkg:gem/curses#lib/curses.rb:12
    def doupdate; end

    # pkg:gem/curses#lib/curses.rb:12
    def echo; end

    # pkg:gem/curses#lib/curses.rb:12
    def erase; end

    # pkg:gem/curses#lib/curses.rb:12
    def flash; end

    # pkg:gem/curses#lib/curses.rb:12
    def flushinp; end

    # pkg:gem/curses#lib/curses.rb:12
    def get_char; end

    # pkg:gem/curses#lib/curses.rb:12
    def getch; end

    # pkg:gem/curses#lib/curses.rb:12
    def getmouse; end

    # pkg:gem/curses#lib/curses.rb:12
    def getstr; end

    # pkg:gem/curses#lib/curses.rb:12
    def has_colors?; end

    # pkg:gem/curses#lib/curses.rb:12
    def inch; end

    # pkg:gem/curses#lib/curses.rb:12
    def init_color(_arg0, _arg1, _arg2, _arg3); end

    # pkg:gem/curses#lib/curses.rb:12
    def init_pair(_arg0, _arg1, _arg2); end

    # pkg:gem/curses#lib/curses.rb:12
    def init_screen; end

    # pkg:gem/curses#lib/curses.rb:12
    def insch(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def insertln; end

    # pkg:gem/curses#lib/curses.rb:12
    def keyboard_encoding; end

    # pkg:gem/curses#lib/curses.rb:12
    def keyboard_encoding=(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def keyname(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def lines; end

    # pkg:gem/curses#lib/curses.rb:12
    def mouseinterval(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def mousemask(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def nl; end

    # pkg:gem/curses#lib/curses.rb:12
    def nocbreak; end

    # pkg:gem/curses#lib/curses.rb:12
    def nocrmode; end

    # pkg:gem/curses#lib/curses.rb:12
    def noecho; end

    # pkg:gem/curses#lib/curses.rb:12
    def nonl; end

    # pkg:gem/curses#lib/curses.rb:12
    def noraw; end

    # pkg:gem/curses#lib/curses.rb:12
    def pair_content(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def pair_number(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def raw; end

    # pkg:gem/curses#lib/curses.rb:12
    def refresh; end

    # pkg:gem/curses#lib/curses.rb:12
    def reset_color_pairs; end

    # pkg:gem/curses#lib/curses.rb:12
    def reset_prog_mode; end

    # pkg:gem/curses#lib/curses.rb:12
    def resize(_arg0, _arg1); end

    # pkg:gem/curses#lib/curses.rb:12
    def resizeterm(_arg0, _arg1); end

    # pkg:gem/curses#lib/curses.rb:12
    def scrl(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def setpos(_arg0, _arg1); end

    # pkg:gem/curses#lib/curses.rb:12
    def setscrreg(_arg0, _arg1); end

    # pkg:gem/curses#lib/curses.rb:12
    def standend; end

    # pkg:gem/curses#lib/curses.rb:12
    def standout; end

    # pkg:gem/curses#lib/curses.rb:12
    def start_color; end

    # pkg:gem/curses#lib/curses.rb:12
    def stdscr; end

    # pkg:gem/curses#lib/curses.rb:12
    def support_extended_colors?; end

    # pkg:gem/curses#lib/curses.rb:12
    def terminal_encoding; end

    # pkg:gem/curses#lib/curses.rb:12
    def terminal_encoding=(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def timeout=(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def unget_char(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def ungetch(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def ungetmouse(_arg0); end

    # pkg:gem/curses#lib/curses.rb:12
    def use_default_colors; end
  end
end

Curses::ALL_MOUSE_EVENTS = T.let(T.unsafe(nil), Integer)
Curses::A_ALTCHARSET = T.let(T.unsafe(nil), Integer)
Curses::A_ATTRIBUTES = T.let(T.unsafe(nil), Integer)
Curses::A_BLINK = T.let(T.unsafe(nil), Integer)
Curses::A_BOLD = T.let(T.unsafe(nil), Integer)
Curses::A_CHARTEXT = T.let(T.unsafe(nil), Integer)
Curses::A_COLOR = T.let(T.unsafe(nil), Integer)
Curses::A_DIM = T.let(T.unsafe(nil), Integer)
Curses::A_HORIZONTAL = T.let(T.unsafe(nil), Integer)
Curses::A_INVIS = T.let(T.unsafe(nil), Integer)
Curses::A_LEFT = T.let(T.unsafe(nil), Integer)
Curses::A_LOW = T.let(T.unsafe(nil), Integer)
Curses::A_NORMAL = T.let(T.unsafe(nil), Integer)
Curses::A_PROTECT = T.let(T.unsafe(nil), Integer)
Curses::A_REVERSE = T.let(T.unsafe(nil), Integer)
Curses::A_RIGHT = T.let(T.unsafe(nil), Integer)
Curses::A_STANDOUT = T.let(T.unsafe(nil), Integer)
Curses::A_TOP = T.let(T.unsafe(nil), Integer)
Curses::A_UNDERLINE = T.let(T.unsafe(nil), Integer)
Curses::A_VERTICAL = T.let(T.unsafe(nil), Integer)
Curses::BUTTON1_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON1_DOUBLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON1_PRESSED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON1_RELEASED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON1_TRIPLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON2_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON2_DOUBLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON2_PRESSED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON2_RELEASED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON2_TRIPLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON3_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON3_DOUBLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON3_PRESSED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON3_RELEASED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON3_TRIPLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON4_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON4_DOUBLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON4_PRESSED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON4_RELEASED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON4_TRIPLE_CLICKED = T.let(T.unsafe(nil), Integer)
Curses::BUTTON_ALT = T.let(T.unsafe(nil), Integer)
Curses::BUTTON_CTRL = T.let(T.unsafe(nil), Integer)
Curses::BUTTON_SHIFT = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
class Curses::BadArgumentError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::BadStateError < ::Curses::Error; end

Curses::COLOR_BLACK = T.let(T.unsafe(nil), Integer)
Curses::COLOR_BLUE = T.let(T.unsafe(nil), Integer)
Curses::COLOR_CYAN = T.let(T.unsafe(nil), Integer)
Curses::COLOR_GREEN = T.let(T.unsafe(nil), Integer)
Curses::COLOR_MAGENTA = T.let(T.unsafe(nil), Integer)
Curses::COLOR_RED = T.let(T.unsafe(nil), Integer)
Curses::COLOR_WHITE = T.let(T.unsafe(nil), Integer)
Curses::COLOR_YELLOW = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
class Curses::ConnectedError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::CurrentError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::Error < ::StandardError; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::Field
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5); end

  # pkg:gem/curses#lib/curses.rb:12
  def back; end

  # pkg:gem/curses#lib/curses.rb:12
  def back=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def buffer(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def dynamic_height; end

  # pkg:gem/curses#lib/curses.rb:12
  def dynamic_width; end

  # pkg:gem/curses#lib/curses.rb:12
  def fore; end

  # pkg:gem/curses#lib/curses.rb:12
  def fore=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def height; end

  # pkg:gem/curses#lib/curses.rb:12
  def leftcol; end

  # pkg:gem/curses#lib/curses.rb:12
  def max; end

  # pkg:gem/curses#lib/curses.rb:12
  def max=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def nbuffers; end

  # pkg:gem/curses#lib/curses.rb:12
  def offscreen; end

  # pkg:gem/curses#lib/curses.rb:12
  def opts; end

  # pkg:gem/curses#lib/curses.rb:12
  def opts_off(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def opts_on(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_back(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_buffer(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_fore(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_max(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_type(*_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def toprow; end

  # pkg:gem/curses#lib/curses.rb:12
  def width; end
end

# pkg:gem/curses#lib/curses.rb:12
class Curses::Form
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def driver(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def post; end

  # pkg:gem/curses#lib/curses.rb:12
  def scale; end

  # pkg:gem/curses#lib/curses.rb:12
  def set_sub(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_win(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def unpost; end
end

# pkg:gem/curses#lib/curses.rb:12
class Curses::InvalidFieldError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::Item
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def ==(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def description; end

  # pkg:gem/curses#lib/curses.rb:12
  def name; end

  # pkg:gem/curses#lib/curses.rb:12
  def opts; end

  # pkg:gem/curses#lib/curses.rb:12
  def opts_off(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def opts_on(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_opts(_arg0); end
end

Curses::KEY_A1 = T.let(T.unsafe(nil), Integer)
Curses::KEY_A3 = T.let(T.unsafe(nil), Integer)
Curses::KEY_B2 = T.let(T.unsafe(nil), Integer)
Curses::KEY_BACKSPACE = T.let(T.unsafe(nil), Integer)
Curses::KEY_BEG = T.let(T.unsafe(nil), Integer)
Curses::KEY_BREAK = T.let(T.unsafe(nil), Integer)
Curses::KEY_BTAB = T.let(T.unsafe(nil), Integer)
Curses::KEY_C1 = T.let(T.unsafe(nil), Integer)
Curses::KEY_C3 = T.let(T.unsafe(nil), Integer)
Curses::KEY_CANCEL = T.let(T.unsafe(nil), Integer)
Curses::KEY_CATAB = T.let(T.unsafe(nil), Integer)
Curses::KEY_CLEAR = T.let(T.unsafe(nil), Integer)
Curses::KEY_CLOSE = T.let(T.unsafe(nil), Integer)
Curses::KEY_COMMAND = T.let(T.unsafe(nil), Integer)
Curses::KEY_COPY = T.let(T.unsafe(nil), Integer)
Curses::KEY_CREATE = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTAB = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_A = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_B = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_C = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_D = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_E = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_F = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_G = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_H = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_I = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_J = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_K = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_L = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_M = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_N = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_O = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_P = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_Q = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_R = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_S = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_T = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_U = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_V = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_W = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_X = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_Y = T.let(T.unsafe(nil), Integer)
Curses::KEY_CTRL_Z = T.let(T.unsafe(nil), Integer)
Curses::KEY_DC = T.let(T.unsafe(nil), Integer)
Curses::KEY_DL = T.let(T.unsafe(nil), Integer)
Curses::KEY_DOWN = T.let(T.unsafe(nil), Integer)
Curses::KEY_EIC = T.let(T.unsafe(nil), Integer)
Curses::KEY_END = T.let(T.unsafe(nil), Integer)
Curses::KEY_ENTER = T.let(T.unsafe(nil), Integer)
Curses::KEY_EOL = T.let(T.unsafe(nil), Integer)
Curses::KEY_EOS = T.let(T.unsafe(nil), Integer)
Curses::KEY_EXIT = T.let(T.unsafe(nil), Integer)
Curses::KEY_F0 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F1 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F10 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F11 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F12 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F13 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F14 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F15 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F16 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F17 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F18 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F19 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F2 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F20 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F21 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F22 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F23 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F24 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F25 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F26 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F27 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F28 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F29 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F3 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F30 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F31 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F32 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F33 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F34 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F35 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F36 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F37 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F38 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F39 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F4 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F40 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F41 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F42 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F43 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F44 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F45 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F46 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F47 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F48 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F49 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F5 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F50 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F51 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F52 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F53 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F54 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F55 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F56 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F57 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F58 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F59 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F6 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F60 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F61 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F62 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F63 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F7 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F8 = T.let(T.unsafe(nil), Integer)
Curses::KEY_F9 = T.let(T.unsafe(nil), Integer)
Curses::KEY_FIND = T.let(T.unsafe(nil), Integer)
Curses::KEY_HELP = T.let(T.unsafe(nil), Integer)
Curses::KEY_HOME = T.let(T.unsafe(nil), Integer)
Curses::KEY_IC = T.let(T.unsafe(nil), Integer)
Curses::KEY_IL = T.let(T.unsafe(nil), Integer)
Curses::KEY_LEFT = T.let(T.unsafe(nil), Integer)
Curses::KEY_LL = T.let(T.unsafe(nil), Integer)
Curses::KEY_MARK = T.let(T.unsafe(nil), Integer)
Curses::KEY_MAX = T.let(T.unsafe(nil), Integer)
Curses::KEY_MESSAGE = T.let(T.unsafe(nil), Integer)
Curses::KEY_MIN = T.let(T.unsafe(nil), Integer)
Curses::KEY_MOUSE = T.let(T.unsafe(nil), Integer)
Curses::KEY_MOVE = T.let(T.unsafe(nil), Integer)
Curses::KEY_NEXT = T.let(T.unsafe(nil), Integer)
Curses::KEY_NPAGE = T.let(T.unsafe(nil), Integer)
Curses::KEY_OPEN = T.let(T.unsafe(nil), Integer)
Curses::KEY_OPTIONS = T.let(T.unsafe(nil), Integer)
Curses::KEY_PPAGE = T.let(T.unsafe(nil), Integer)
Curses::KEY_PREVIOUS = T.let(T.unsafe(nil), Integer)
Curses::KEY_PRINT = T.let(T.unsafe(nil), Integer)
Curses::KEY_REDO = T.let(T.unsafe(nil), Integer)
Curses::KEY_REFERENCE = T.let(T.unsafe(nil), Integer)
Curses::KEY_REFRESH = T.let(T.unsafe(nil), Integer)
Curses::KEY_REPLACE = T.let(T.unsafe(nil), Integer)
Curses::KEY_RESET = T.let(T.unsafe(nil), Integer)
Curses::KEY_RESIZE = T.let(T.unsafe(nil), Integer)
Curses::KEY_RESTART = T.let(T.unsafe(nil), Integer)
Curses::KEY_RESUME = T.let(T.unsafe(nil), Integer)
Curses::KEY_RIGHT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SAVE = T.let(T.unsafe(nil), Integer)
Curses::KEY_SBEG = T.let(T.unsafe(nil), Integer)
Curses::KEY_SCANCEL = T.let(T.unsafe(nil), Integer)
Curses::KEY_SCOMMAND = T.let(T.unsafe(nil), Integer)
Curses::KEY_SCOPY = T.let(T.unsafe(nil), Integer)
Curses::KEY_SCREATE = T.let(T.unsafe(nil), Integer)
Curses::KEY_SDC = T.let(T.unsafe(nil), Integer)
Curses::KEY_SDL = T.let(T.unsafe(nil), Integer)
Curses::KEY_SELECT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SEND = T.let(T.unsafe(nil), Integer)
Curses::KEY_SEOL = T.let(T.unsafe(nil), Integer)
Curses::KEY_SEXIT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SF = T.let(T.unsafe(nil), Integer)
Curses::KEY_SFIND = T.let(T.unsafe(nil), Integer)
Curses::KEY_SHELP = T.let(T.unsafe(nil), Integer)
Curses::KEY_SHOME = T.let(T.unsafe(nil), Integer)
Curses::KEY_SIC = T.let(T.unsafe(nil), Integer)
Curses::KEY_SLEFT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SMESSAGE = T.let(T.unsafe(nil), Integer)
Curses::KEY_SMOVE = T.let(T.unsafe(nil), Integer)
Curses::KEY_SNEXT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SOPTIONS = T.let(T.unsafe(nil), Integer)
Curses::KEY_SPREVIOUS = T.let(T.unsafe(nil), Integer)
Curses::KEY_SPRINT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SR = T.let(T.unsafe(nil), Integer)
Curses::KEY_SREDO = T.let(T.unsafe(nil), Integer)
Curses::KEY_SREPLACE = T.let(T.unsafe(nil), Integer)
Curses::KEY_SRESET = T.let(T.unsafe(nil), Integer)
Curses::KEY_SRIGHT = T.let(T.unsafe(nil), Integer)
Curses::KEY_SRSUME = T.let(T.unsafe(nil), Integer)
Curses::KEY_SSAVE = T.let(T.unsafe(nil), Integer)
Curses::KEY_SSUSPEND = T.let(T.unsafe(nil), Integer)
Curses::KEY_STAB = T.let(T.unsafe(nil), Integer)
Curses::KEY_SUNDO = T.let(T.unsafe(nil), Integer)
Curses::KEY_SUSPEND = T.let(T.unsafe(nil), Integer)
Curses::KEY_UNDO = T.let(T.unsafe(nil), Integer)
Curses::KEY_UP = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
module Curses::Key; end

Curses::Key::A1 = T.let(T.unsafe(nil), Integer)
Curses::Key::A3 = T.let(T.unsafe(nil), Integer)
Curses::Key::B2 = T.let(T.unsafe(nil), Integer)
Curses::Key::BACKSPACE = T.let(T.unsafe(nil), Integer)
Curses::Key::BEG = T.let(T.unsafe(nil), Integer)
Curses::Key::BREAK = T.let(T.unsafe(nil), Integer)
Curses::Key::BTAB = T.let(T.unsafe(nil), Integer)
Curses::Key::C1 = T.let(T.unsafe(nil), Integer)
Curses::Key::C3 = T.let(T.unsafe(nil), Integer)
Curses::Key::CANCEL = T.let(T.unsafe(nil), Integer)
Curses::Key::CATAB = T.let(T.unsafe(nil), Integer)
Curses::Key::CLEAR = T.let(T.unsafe(nil), Integer)
Curses::Key::CLOSE = T.let(T.unsafe(nil), Integer)
Curses::Key::COMMAND = T.let(T.unsafe(nil), Integer)
Curses::Key::COPY = T.let(T.unsafe(nil), Integer)
Curses::Key::CREATE = T.let(T.unsafe(nil), Integer)
Curses::Key::CTAB = T.let(T.unsafe(nil), Integer)
Curses::Key::DC = T.let(T.unsafe(nil), Integer)
Curses::Key::DL = T.let(T.unsafe(nil), Integer)
Curses::Key::DOWN = T.let(T.unsafe(nil), Integer)
Curses::Key::EIC = T.let(T.unsafe(nil), Integer)
Curses::Key::END = T.let(T.unsafe(nil), Integer)
Curses::Key::ENTER = T.let(T.unsafe(nil), Integer)
Curses::Key::EOL = T.let(T.unsafe(nil), Integer)
Curses::Key::EOS = T.let(T.unsafe(nil), Integer)
Curses::Key::EXIT = T.let(T.unsafe(nil), Integer)
Curses::Key::F0 = T.let(T.unsafe(nil), Integer)
Curses::Key::F1 = T.let(T.unsafe(nil), Integer)
Curses::Key::F10 = T.let(T.unsafe(nil), Integer)
Curses::Key::F11 = T.let(T.unsafe(nil), Integer)
Curses::Key::F12 = T.let(T.unsafe(nil), Integer)
Curses::Key::F13 = T.let(T.unsafe(nil), Integer)
Curses::Key::F14 = T.let(T.unsafe(nil), Integer)
Curses::Key::F15 = T.let(T.unsafe(nil), Integer)
Curses::Key::F16 = T.let(T.unsafe(nil), Integer)
Curses::Key::F17 = T.let(T.unsafe(nil), Integer)
Curses::Key::F18 = T.let(T.unsafe(nil), Integer)
Curses::Key::F19 = T.let(T.unsafe(nil), Integer)
Curses::Key::F2 = T.let(T.unsafe(nil), Integer)
Curses::Key::F20 = T.let(T.unsafe(nil), Integer)
Curses::Key::F21 = T.let(T.unsafe(nil), Integer)
Curses::Key::F22 = T.let(T.unsafe(nil), Integer)
Curses::Key::F23 = T.let(T.unsafe(nil), Integer)
Curses::Key::F24 = T.let(T.unsafe(nil), Integer)
Curses::Key::F25 = T.let(T.unsafe(nil), Integer)
Curses::Key::F26 = T.let(T.unsafe(nil), Integer)
Curses::Key::F27 = T.let(T.unsafe(nil), Integer)
Curses::Key::F28 = T.let(T.unsafe(nil), Integer)
Curses::Key::F29 = T.let(T.unsafe(nil), Integer)
Curses::Key::F3 = T.let(T.unsafe(nil), Integer)
Curses::Key::F30 = T.let(T.unsafe(nil), Integer)
Curses::Key::F31 = T.let(T.unsafe(nil), Integer)
Curses::Key::F32 = T.let(T.unsafe(nil), Integer)
Curses::Key::F33 = T.let(T.unsafe(nil), Integer)
Curses::Key::F34 = T.let(T.unsafe(nil), Integer)
Curses::Key::F35 = T.let(T.unsafe(nil), Integer)
Curses::Key::F36 = T.let(T.unsafe(nil), Integer)
Curses::Key::F37 = T.let(T.unsafe(nil), Integer)
Curses::Key::F38 = T.let(T.unsafe(nil), Integer)
Curses::Key::F39 = T.let(T.unsafe(nil), Integer)
Curses::Key::F4 = T.let(T.unsafe(nil), Integer)
Curses::Key::F40 = T.let(T.unsafe(nil), Integer)
Curses::Key::F41 = T.let(T.unsafe(nil), Integer)
Curses::Key::F42 = T.let(T.unsafe(nil), Integer)
Curses::Key::F43 = T.let(T.unsafe(nil), Integer)
Curses::Key::F44 = T.let(T.unsafe(nil), Integer)
Curses::Key::F45 = T.let(T.unsafe(nil), Integer)
Curses::Key::F46 = T.let(T.unsafe(nil), Integer)
Curses::Key::F47 = T.let(T.unsafe(nil), Integer)
Curses::Key::F48 = T.let(T.unsafe(nil), Integer)
Curses::Key::F49 = T.let(T.unsafe(nil), Integer)
Curses::Key::F5 = T.let(T.unsafe(nil), Integer)
Curses::Key::F50 = T.let(T.unsafe(nil), Integer)
Curses::Key::F51 = T.let(T.unsafe(nil), Integer)
Curses::Key::F52 = T.let(T.unsafe(nil), Integer)
Curses::Key::F53 = T.let(T.unsafe(nil), Integer)
Curses::Key::F54 = T.let(T.unsafe(nil), Integer)
Curses::Key::F55 = T.let(T.unsafe(nil), Integer)
Curses::Key::F56 = T.let(T.unsafe(nil), Integer)
Curses::Key::F57 = T.let(T.unsafe(nil), Integer)
Curses::Key::F58 = T.let(T.unsafe(nil), Integer)
Curses::Key::F59 = T.let(T.unsafe(nil), Integer)
Curses::Key::F6 = T.let(T.unsafe(nil), Integer)
Curses::Key::F60 = T.let(T.unsafe(nil), Integer)
Curses::Key::F61 = T.let(T.unsafe(nil), Integer)
Curses::Key::F62 = T.let(T.unsafe(nil), Integer)
Curses::Key::F63 = T.let(T.unsafe(nil), Integer)
Curses::Key::F7 = T.let(T.unsafe(nil), Integer)
Curses::Key::F8 = T.let(T.unsafe(nil), Integer)
Curses::Key::F9 = T.let(T.unsafe(nil), Integer)
Curses::Key::FIND = T.let(T.unsafe(nil), Integer)
Curses::Key::HELP = T.let(T.unsafe(nil), Integer)
Curses::Key::HOME = T.let(T.unsafe(nil), Integer)
Curses::Key::IC = T.let(T.unsafe(nil), Integer)
Curses::Key::IL = T.let(T.unsafe(nil), Integer)
Curses::Key::LEFT = T.let(T.unsafe(nil), Integer)
Curses::Key::LL = T.let(T.unsafe(nil), Integer)
Curses::Key::MARK = T.let(T.unsafe(nil), Integer)
Curses::Key::MAX = T.let(T.unsafe(nil), Integer)
Curses::Key::MESSAGE = T.let(T.unsafe(nil), Integer)
Curses::Key::MIN = T.let(T.unsafe(nil), Integer)
Curses::Key::MOUSE = T.let(T.unsafe(nil), Integer)
Curses::Key::MOVE = T.let(T.unsafe(nil), Integer)
Curses::Key::NEXT = T.let(T.unsafe(nil), Integer)
Curses::Key::NPAGE = T.let(T.unsafe(nil), Integer)
Curses::Key::OPEN = T.let(T.unsafe(nil), Integer)
Curses::Key::OPTIONS = T.let(T.unsafe(nil), Integer)
Curses::Key::PPAGE = T.let(T.unsafe(nil), Integer)
Curses::Key::PREVIOUS = T.let(T.unsafe(nil), Integer)
Curses::Key::PRINT = T.let(T.unsafe(nil), Integer)
Curses::Key::REDO = T.let(T.unsafe(nil), Integer)
Curses::Key::REFERENCE = T.let(T.unsafe(nil), Integer)
Curses::Key::REFRESH = T.let(T.unsafe(nil), Integer)
Curses::Key::REPLACE = T.let(T.unsafe(nil), Integer)
Curses::Key::RESET = T.let(T.unsafe(nil), Integer)
Curses::Key::RESIZE = T.let(T.unsafe(nil), Integer)
Curses::Key::RESTART = T.let(T.unsafe(nil), Integer)
Curses::Key::RESUME = T.let(T.unsafe(nil), Integer)
Curses::Key::RIGHT = T.let(T.unsafe(nil), Integer)
Curses::Key::SAVE = T.let(T.unsafe(nil), Integer)
Curses::Key::SBEG = T.let(T.unsafe(nil), Integer)
Curses::Key::SCANCEL = T.let(T.unsafe(nil), Integer)
Curses::Key::SCOMMAND = T.let(T.unsafe(nil), Integer)
Curses::Key::SCOPY = T.let(T.unsafe(nil), Integer)
Curses::Key::SCREATE = T.let(T.unsafe(nil), Integer)
Curses::Key::SDC = T.let(T.unsafe(nil), Integer)
Curses::Key::SDL = T.let(T.unsafe(nil), Integer)
Curses::Key::SELECT = T.let(T.unsafe(nil), Integer)
Curses::Key::SEND = T.let(T.unsafe(nil), Integer)
Curses::Key::SEOL = T.let(T.unsafe(nil), Integer)
Curses::Key::SEXIT = T.let(T.unsafe(nil), Integer)
Curses::Key::SF = T.let(T.unsafe(nil), Integer)
Curses::Key::SFIND = T.let(T.unsafe(nil), Integer)
Curses::Key::SHELP = T.let(T.unsafe(nil), Integer)
Curses::Key::SHOME = T.let(T.unsafe(nil), Integer)
Curses::Key::SIC = T.let(T.unsafe(nil), Integer)
Curses::Key::SLEFT = T.let(T.unsafe(nil), Integer)
Curses::Key::SMESSAGE = T.let(T.unsafe(nil), Integer)
Curses::Key::SMOVE = T.let(T.unsafe(nil), Integer)
Curses::Key::SNEXT = T.let(T.unsafe(nil), Integer)
Curses::Key::SOPTIONS = T.let(T.unsafe(nil), Integer)
Curses::Key::SPREVIOUS = T.let(T.unsafe(nil), Integer)
Curses::Key::SPRINT = T.let(T.unsafe(nil), Integer)
Curses::Key::SR = T.let(T.unsafe(nil), Integer)
Curses::Key::SREDO = T.let(T.unsafe(nil), Integer)
Curses::Key::SREPLACE = T.let(T.unsafe(nil), Integer)
Curses::Key::SRESET = T.let(T.unsafe(nil), Integer)
Curses::Key::SRIGHT = T.let(T.unsafe(nil), Integer)
Curses::Key::SRSUME = T.let(T.unsafe(nil), Integer)
Curses::Key::SSAVE = T.let(T.unsafe(nil), Integer)
Curses::Key::SSUSPEND = T.let(T.unsafe(nil), Integer)
Curses::Key::STAB = T.let(T.unsafe(nil), Integer)
Curses::Key::SUNDO = T.let(T.unsafe(nil), Integer)
Curses::Key::SUSPEND = T.let(T.unsafe(nil), Integer)
Curses::Key::UNDO = T.let(T.unsafe(nil), Integer)
Curses::Key::UP = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
class Curses::Menu
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def back; end

  # pkg:gem/curses#lib/curses.rb:12
  def back=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:76
  def back_pattern; end

  # pkg:gem/curses#lib/curses.rb:72
  def clear_pattern; end

  # pkg:gem/curses#lib/curses.rb:12
  def current_item; end

  # pkg:gem/curses#lib/curses.rb:12
  def current_item=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:32
  def down_item; end

  # pkg:gem/curses#lib/curses.rb:12
  def driver(_arg0); end

  # pkg:gem/curses#lib/curses.rb:52
  def first_item; end

  # pkg:gem/curses#lib/curses.rb:12
  def fore; end

  # pkg:gem/curses#lib/curses.rb:12
  def fore=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def format; end

  # pkg:gem/curses#lib/curses.rb:12
  def item_count; end

  # pkg:gem/curses#lib/curses.rb:12
  def items; end

  # pkg:gem/curses#lib/curses.rb:12
  def items=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:56
  def last_item; end

  # pkg:gem/curses#lib/curses.rb:20
  def left_item; end

  # pkg:gem/curses#lib/curses.rb:12
  def mark; end

  # pkg:gem/curses#lib/curses.rb:12
  def mark=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:60
  def next_item; end

  # pkg:gem/curses#lib/curses.rb:80
  def next_match; end

  # pkg:gem/curses#lib/curses.rb:12
  def opts; end

  # pkg:gem/curses#lib/curses.rb:12
  def opts_off(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def opts_on(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def post; end

  # pkg:gem/curses#lib/curses.rb:64
  def prev_item; end

  # pkg:gem/curses#lib/curses.rb:84
  def prev_match; end

  # pkg:gem/curses#lib/curses.rb:24
  def right_item; end

  # pkg:gem/curses#lib/curses.rb:12
  def scale; end

  # pkg:gem/curses#lib/curses.rb:40
  def scroll_down_line; end

  # pkg:gem/curses#lib/curses.rb:48
  def scroll_down_page; end

  # pkg:gem/curses#lib/curses.rb:36
  def scroll_up_line; end

  # pkg:gem/curses#lib/curses.rb:44
  def scroll_up_page; end

  # pkg:gem/curses#lib/curses.rb:12
  def set_format(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_opts(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_sub(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_win(_arg0); end

  # pkg:gem/curses#lib/curses.rb:68
  def toggle_item; end

  # pkg:gem/curses#lib/curses.rb:12
  def unpost; end

  # pkg:gem/curses#lib/curses.rb:28
  def up_item; end
end

# pkg:gem/curses#lib/curses.rb:12
class Curses::MouseEvent
  # pkg:gem/curses#lib/curses.rb:12
  def bstate; end

  # pkg:gem/curses#lib/curses.rb:12
  def eid; end

  # pkg:gem/curses#lib/curses.rb:12
  def x; end

  # pkg:gem/curses#lib/curses.rb:12
  def y; end

  # pkg:gem/curses#lib/curses.rb:12
  def z; end
end

# pkg:gem/curses#lib/curses.rb:12
class Curses::NoMatchError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::NoRoomError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::NotConnectedError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::NotPostedError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::NotSelectableError < ::Curses::Error; end

Curses::O_ACTIVE = T.let(T.unsafe(nil), Integer)
Curses::O_AUTOSKIP = T.let(T.unsafe(nil), Integer)
Curses::O_BLANK = T.let(T.unsafe(nil), Integer)
Curses::O_DYNAMIC_JUSTIFY = T.let(T.unsafe(nil), Integer)
Curses::O_EDIT = T.let(T.unsafe(nil), Integer)
Curses::O_IGNORECASE = T.let(T.unsafe(nil), Integer)
Curses::O_NONCYCLIC = T.let(T.unsafe(nil), Integer)
Curses::O_NULLOK = T.let(T.unsafe(nil), Integer)
Curses::O_ONEVALUE = T.let(T.unsafe(nil), Integer)
Curses::O_PASSOK = T.let(T.unsafe(nil), Integer)
Curses::O_PUBLIC = T.let(T.unsafe(nil), Integer)
Curses::O_ROWMAJOR = T.let(T.unsafe(nil), Integer)
Curses::O_SELECTABLE = T.let(T.unsafe(nil), Integer)
Curses::O_SHOWDESC = T.let(T.unsafe(nil), Integer)
Curses::O_SHOWMATCH = T.let(T.unsafe(nil), Integer)
Curses::O_STATIC = T.let(T.unsafe(nil), Integer)
Curses::O_VISIBLE = T.let(T.unsafe(nil), Integer)
Curses::O_WRAP = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
class Curses::Pad < ::Curses::Window
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def noutrefresh(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5); end

  # pkg:gem/curses#lib/curses.rb:12
  def refresh(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5); end

  # pkg:gem/curses#lib/curses.rb:12
  def subpad(_arg0, _arg1, _arg2, _arg3); end
end

# pkg:gem/curses#lib/curses.rb:12
class Curses::PostedError < ::Curses::Error; end

Curses::REPORT_MOUSE_POSITION = T.let(T.unsafe(nil), Integer)
Curses::REQ_BACK_PATTERN = T.let(T.unsafe(nil), Integer)
Curses::REQ_BEG_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_BEG_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_CLEAR_PATTERN = T.let(T.unsafe(nil), Integer)
Curses::REQ_CLR_EOF = T.let(T.unsafe(nil), Integer)
Curses::REQ_CLR_EOL = T.let(T.unsafe(nil), Integer)
Curses::REQ_CLR_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_DEL_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_DEL_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_DEL_PREV = T.let(T.unsafe(nil), Integer)
Curses::REQ_DEL_WORD = T.let(T.unsafe(nil), Integer)
Curses::REQ_DOWN_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_DOWN_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_DOWN_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_END_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_END_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_FIRST_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_FIRST_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_FIRST_PAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_INS_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_INS_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_INS_MODE = T.let(T.unsafe(nil), Integer)
Curses::REQ_LAST_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_LAST_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_LAST_PAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_LEFT_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_LEFT_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_LEFT_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEW_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_CHOICE = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_MATCH = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_PAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_NEXT_WORD = T.let(T.unsafe(nil), Integer)
Curses::REQ_OVL_MODE = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_CHOICE = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_LINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_MATCH = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_PAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_PREV_WORD = T.let(T.unsafe(nil), Integer)
Curses::REQ_RIGHT_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_RIGHT_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_RIGHT_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_BCHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_BHPAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_BLINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_BPAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_DLINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_DPAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_FCHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_FHPAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_FLINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_FPAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_HBHALF = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_HBLINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_HFHALF = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_HFLINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_ULINE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SCR_UPAGE = T.let(T.unsafe(nil), Integer)
Curses::REQ_SFIRST_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_SLAST_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_SNEXT_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_SPREV_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_TOGGLE_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_UP_CHAR = T.let(T.unsafe(nil), Integer)
Curses::REQ_UP_FIELD = T.let(T.unsafe(nil), Integer)
Curses::REQ_UP_ITEM = T.let(T.unsafe(nil), Integer)
Curses::REQ_VALIDATION = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
class Curses::RequestDeniedError < ::Curses::Error; end

# pkg:gem/curses#lib/curses.rb:12
class Curses::Screen
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(*_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def set_term; end
end

# pkg:gem/curses#lib/curses.rb:12
class Curses::SystemError < ::Curses::Error; end

Curses::TYPE_ALNUM = T.let(T.unsafe(nil), Integer)
Curses::TYPE_ALPHA = T.let(T.unsafe(nil), Integer)
Curses::TYPE_ENUM = T.let(T.unsafe(nil), Integer)
Curses::TYPE_INTEGER = T.let(T.unsafe(nil), Integer)
Curses::TYPE_NUMERIC = T.let(T.unsafe(nil), Integer)
Curses::TYPE_REGEXP = T.let(T.unsafe(nil), Integer)

# pkg:gem/curses#lib/curses.rb:12
class Curses::UnknownCommandError < ::Curses::Error; end

Curses::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/curses#lib/curses.rb:12
class Curses::Window
  # pkg:gem/curses#lib/curses.rb:12
  def initialize(_arg0, _arg1, _arg2, _arg3); end

  # pkg:gem/curses#lib/curses.rb:12
  def <<(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def addch(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def addstr(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def attr_get; end

  # pkg:gem/curses#lib/curses.rb:12
  def attr_set(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def attroff(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def attron(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def attrset(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def begx; end

  # pkg:gem/curses#lib/curses.rb:12
  def begy; end

  # pkg:gem/curses#lib/curses.rb:12
  def bkgd(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def bkgdset(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def box(*_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def chgat(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def clear; end

  # pkg:gem/curses#lib/curses.rb:12
  def close; end

  # pkg:gem/curses#lib/curses.rb:12
  def clrtoeol; end

  # pkg:gem/curses#lib/curses.rb:12
  def color_set(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def curx; end

  # pkg:gem/curses#lib/curses.rb:12
  def cury; end

  # pkg:gem/curses#lib/curses.rb:12
  def delch; end

  # pkg:gem/curses#lib/curses.rb:12
  def deleteln; end

  # pkg:gem/curses#lib/curses.rb:12
  def derwin(_arg0, _arg1, _arg2, _arg3); end

  # pkg:gem/curses#lib/curses.rb:12
  def erase; end

  # pkg:gem/curses#lib/curses.rb:12
  def get_char; end

  # pkg:gem/curses#lib/curses.rb:12
  def getbkgd; end

  # pkg:gem/curses#lib/curses.rb:12
  def getch; end

  # pkg:gem/curses#lib/curses.rb:12
  def getstr; end

  # pkg:gem/curses#lib/curses.rb:12
  def idlok(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def inch; end

  # pkg:gem/curses#lib/curses.rb:12
  def insch(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def insertln; end

  # pkg:gem/curses#lib/curses.rb:12
  def keypad(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def keypad=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def line_touched?(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def maxx; end

  # pkg:gem/curses#lib/curses.rb:12
  def maxy; end

  # pkg:gem/curses#lib/curses.rb:12
  def move(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def move_relative(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def nodelay=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def noutrefresh; end

  # pkg:gem/curses#lib/curses.rb:12
  def redraw; end

  # pkg:gem/curses#lib/curses.rb:12
  def refresh; end

  # pkg:gem/curses#lib/curses.rb:12
  def resize(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def scrl(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def scroll; end

  # pkg:gem/curses#lib/curses.rb:12
  def scrollok(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def setpos(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def setscrreg(_arg0, _arg1); end

  # pkg:gem/curses#lib/curses.rb:12
  def standend; end

  # pkg:gem/curses#lib/curses.rb:12
  def standout; end

  # pkg:gem/curses#lib/curses.rb:12
  def subwin(_arg0, _arg1, _arg2, _arg3); end

  # pkg:gem/curses#lib/curses.rb:12
  def timeout=(_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def touch; end

  # pkg:gem/curses#lib/curses.rb:12
  def touch_line(*_arg0); end

  # pkg:gem/curses#lib/curses.rb:12
  def touched?; end

  # pkg:gem/curses#lib/curses.rb:12
  def untouch; end
end
